create table member(
    name varchar(255),
    age number,
    gender varchar(10),
    address varchar(255),
    id varchar(255),
    pw varchar(255),
    primary key(id)
);

create table freeboard(
    bno number not null generated by default as identity,
    title varchar2(255) not null,
    content varchar2(4000),
    writer varchar2(255) not null,
    regdate date not null default sysdate ,
    viewcnt number not null default 0,
    primary key(bno)
);