create table member(
    name varchar(255),
    age number,
    gender varchar(10),
    address varchar(255),
    id varchar(255),
    pw varchar(255),
    primary key(id)
);

create table mypicks(
    id number not null generated by default as identity,
    userid varchar2(255) not null,
    restr_num number not null,
    primary key(id)
);

create table freeboard(
    bno number not null generated by default as identity,
    title varchar2(255) not null,
    content varchar2(4000),
    writer varchar2(255) not null,
    regdate date not null default sysdate ,
    viewcnt number not null default 0,
    primary key(bno)
);

alter table freeboard add replycnt number default 0 not null;

alter table freeboard add file_name varchar2(100);
alter table freeboard add org_file_name varchar2(100);

create table reply(
    rno number not null generated by default as identity,
    bno number not null,
    content varchar2(1000),
    writer varchar2(255) not null,
    regdate date not null default sysdate,
    primary key(rno)
);

alter table reply
add constraint fk_bno foreign key (bno)
references freeboard (bno)
on delete cascade
on update cascade;

